server:
  port: 8089

spring:
  application:
    name: external-stubs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    team.ylab.tools.stubs: INFO
